# Generated by Django 5.2.7 on 2025-10-16 09:27

import django.db.models.deletion
import grandview.settings
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVerificationPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Agent Verification', max_length=100)),
                ('image', models.ImageField(storage=grandview.settings.S3MediaStorage(default_acl='public-read'), upload_to='premium_packages/')),
                ('validity_days', models.IntegerField(default=365)),
                ('description', models.TextField(default='Become a verified agent to unlock withdrawals and exclusive weekly bonuses.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AgentPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_purchases', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='premium.agentverificationpackage')),
            ],
            options={
                'unique_together': {('user', 'package', 'status')},
            },
        ),
        migrations.CreateModel(
            name='CashbackBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claim_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('claimed', models.BooleanField(default=False)),
                ('claim_date', models.DateTimeField(blank=True, null=True)),
                ('agent_purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='premium.agentpurchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_cashback_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('claim_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('claimed', models.BooleanField(default=False)),
                ('claim_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_bonuses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
