# Generated by Django 5.2.7 on 2025-10-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified_agent',
            field=models.BooleanField(default=False),
        ),
    ]
