# Generated by Django 5.2.7 on 2025-10-08 19:04

from django.db import migrations

from accounts import models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
           model_name='CustomUser',
           name='last_support_view',
           field=models.DateTimeField(null=True, blank=True),
       )
    ]
