# Generated by Django 5.2.7 on 2025-10-09 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('EARNING', 'Earning'), ('COMMISSION', 'Commission'), ('PURCHASE', 'Purchase'), ('WITHDRAW_PENDING', 'Withdraw Pending'), ('WITHDRAW_COMPLETED', 'Withdraw Completed'), ('WITHDRAW_CANCELLED', 'Withdraw Cancelled'), ('WITHDRAW_REFUND', 'Withdraw Refund')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('balance_type', models.CharField(blank=True, choices=[('VIEWS_EARNINGS', 'Views Earnings'), ('DEPOSIT', 'Deposit'), ('REFERRAL', 'Referral')], max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('views_earnings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('referral_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=50, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=20, null=True)),
                ('mpesa_code', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_type', models.CharField(choices=[('VIEWS_EARNINGS', 'Views Earnings'), ('DEPOSIT', 'Deposit'), ('REFERRAL', 'Referral')], max_length=20)),
                ('from_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('from_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mpesa_number', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('pending_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_pending', to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallet.wallet')),
            ],
        ),
    ]
