# Generated by Django 5.2.7 on 2025-10-07 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='balance_type',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('EARNING', 'Earning'), ('COMMISSION', 'Commission'), ('WITHDRAW_PENDING', 'Withdraw Pending'), ('WITHDRAW_COMPLETED', 'Withdraw Completed'), ('WITHDRAW_CANCELLED', 'Withdraw Cancelled'), ('WITHDRAW_REFUND', 'Withdraw Refund'), ('INSTALLMENT_PAYMENT', 'Installment Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='from_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='from_earnings',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='mpesa_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='pending_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_pending', to='wallet.transaction'),
        ),
    ]
