# Generated by Django 5.2.7 on 2025-10-11 10:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='mpesa_code',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='balance_type',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(default=datetime.datetime(2025, 10, 11, 10, 40, 30, 620650, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW_PENDING', 'Withdraw Pending'), ('WITHDRAW_COMPLETED', 'Withdraw Completed'), ('WITHDRAW_CANCELLED', 'Withdraw Cancelled'), ('WITHDRAW_REFUND', 'Withdraw Refund'), ('COMMISSION', 'Commission'), ('EARNING', 'Earning'), ('ORDER', 'Order')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='balance_type',
            field=models.CharField(choices=[('main_balance', 'Main Balance'), ('referral_balance', 'Referral Balance')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
    ]
