# Generated by Django 5.2.7 on 2025-10-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20251009_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='Deposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        )
    ]
