# Generated by Django 5.2.4 on 2025-09-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('PURCHASE', 'Package Purchase'), ('COMMISSION', 'Referral Commission'), ('WITHDRAW_PENDING', 'Withdrawal Pending'), ('WITHDRAW_COMPLETED', 'Withdrawal Completed'), ('WITHDRAW_CANCELLED', 'Withdrawal Cancelled'), ('WITHDRAW_REFUND', 'Withdrawal Refund')], max_length=20),
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_type', models.CharField(choices=[('main_balance', 'Main Balance'), ('referral_balance', 'Referral Balance')], max_length=20)),
                ('from_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('from_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('pending_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wallet.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='wallet.wallet')),
            ],
        ),
    ]
