# Generated by Django 5.2.4 on 2025-09-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_alter_transaction_transaction_type_withdrawal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='main_balance',
            new_name='deposit_balance',
        ),
        migrations.AddField(
            model_name='wallet',
            name='views_earnings_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('PURCHASE', 'Package Purchase'), ('COMMISSION', 'Referral Commission'), ('EARNING', 'Views Earnings'), ('WITHDRAW_PENDING', 'Withdrawal Pending'), ('WITHDRAW_COMPLETED', 'Withdrawal Completed'), ('WITHDRAW_CANCELLED', 'Withdrawal Cancelled'), ('WITHDRAW_REFUND', 'Withdrawal Refund')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='pending_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_pending', to='wallet.transaction'),
        ),
    ]
