# Generated by Django 5.2.4 on 2025-09-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_rename_main_balance_wallet_deposit_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(),
        ),
    ]
