# Generated by Django 5.2.4 on 2025-09-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('PURCHASE', 'Package Purchase'), ('COMMISSION', 'Referral Commission'), ('EARNING', 'Views Earnings'), ('WITHDRAW_PENDING', 'Withdrawal Pending'), ('WITHDRAW_COMPLETED', 'Withdrawal Completed'), ('WITHDRAW_REFUND', 'Withdrawal Refund'), ('INSTALLMENT_PAYMENT', 'Installment Payment')], max_length=20),
        ),
    ]
