# Generated by Django 5.2.4 on 2025-09-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('views_earnings', 'Views Earnings'), ('referral', 'Referral'), ('main', 'Main')], default='deposit', max_length=20),
        ),
    ]
