# Generated by Django 5.2.4 on 2025-09-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_transaction_balance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('PURCHASE', 'Package Purchase'), ('COMMISSION', 'Referral Commission'), ('EARNING', 'Views Earnings'), ('WITHDRAW_PENDING', 'Withdrawal Pending'), ('WITHDRAW_COMPLETED', 'Withdrawal Completed'), ('WITHDRAW_REFUND', 'Withdrawal Refund'), ('WITHDRAW_CANCELLED', 'Withdrawal Cancelled'), ('INSTALLMENT_PAYMENT', 'Installment Payment')], max_length=20),
        ),
    ]
