# Generated by Django 5.2.4 on 2025-09-23 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0009_deposit_mpesa_code_deposit_mpesa_receipt_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='mpesa_number',
            field=models.CharField(default=datetime.datetime(2025, 9, 23, 16, 21, 51, 61312, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
