# Generated by Django 5.2.4 on 2025-09-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0012_alter_deposit_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
