# Generated by Django 5.2.4 on 2025-09-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_deposit_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawal',
            name='mpesa_number',
            field=models.CharField(max_length=50),
        ),
    ]
