# Generated by Django 5.2.4 on 2025-09-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_alter_withdrawal_mpesa_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
