# Generated by Django 5.2.7 on 2025-10-07 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0018_alter_deposit_mpesa_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='deposit_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='withdrawal',
            old_name='request_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='mpesa_code',
        ),
        migrations.AlterField(
            model_name='deposit',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_type',
            field=models.CharField(blank=True, choices=[('VIEWS_EARNINGS', 'Views Earnings'), ('DEPOSIT', 'Deposit'), ('REFERRAL', 'Referral')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('EARNING', 'Earning'), ('COMMISSION', 'Commission'), ('PURCHASE', 'Purchase'), ('WITHDRAW_PENDING', 'Withdraw Pending'), ('WITHDRAW_COMPLETED', 'Withdraw Completed'), ('WITHDRAW_CANCELLED', 'Withdraw Cancelled'), ('WITHDRAW_REFUND', 'Withdraw Refund')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='balance_type',
            field=models.CharField(choices=[('VIEWS_EARNINGS', 'Views Earnings'), ('DEPOSIT', 'Deposit'), ('REFERRAL', 'Referral')], max_length=20),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='mpesa_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='pending_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_pending', to='wallet.transaction'),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10),
        ),
    ]
