# Generated by Django 5.2.7 on 2025-10-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0019_rename_deposit_date_deposit_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
