# Generated by Django 5.2.7 on 2025-10-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0020_deposit_mpesa_code_deposit_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='mpesa_code',
        ),
    ]
