# Generated by Django 5.2.7 on 2025-10-08 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0021_remove_deposit_mpesa_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
