# Generated by Django 5.2.7 on 2025-10-09 12:59

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='adverts/'),
        ),
    ]
