# Generated by Django 5.2.7 on 2025-10-09 13:38

import grandview.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_advert_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='file',
            field=models.FileField(storage=grandview.settings.S3MediaStorage(), upload_to='adverts/'),
        ),
    ]
