# Generated by Django 5.2.4 on 2025-09-13 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverts', '0002_alter_submission_earnings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'advert', 'submission_date')},
        ),
        migrations.AlterField(
            model_name='submission',
            name='earnings',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='submission',
            name='screenshot',
            field=models.FileField(upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='views_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
