# Generated by Django 5.2.7 on 2025-10-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, to='dashboard.product'),
        ),
        migrations.AlterField(
            model_name='installmentorder',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='installmentorder',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='installmentorder',
            name='months',
            field=models.PositiveIntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='discounted_total',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]