# Generated by Django 5.2.7 on 2025-10-17 12:17

import django.db.models.deletion
import grandview.settings
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person_name', models.CharField(max_length=255)),
                ('delivery_person_photo', models.ImageField(blank=True, null=True, storage=grandview.settings.S3MediaStorage(default_acl='public-read'), upload_to='delivery_profiles/')),
                ('current_latitude', models.FloatField(default=-1.3101)),
                ('current_longitude', models.FloatField(default=36.8148)),
                ('destination_address', models.TextField()),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('estimated_delivery_time', models.DateTimeField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('EN_ROUTE', 'En Route'), ('DELIVERED', 'Delivered')], default='EN_ROUTE', max_length=20)),
                ('delivery_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='dashboard.order')),
            ],
        ),
    ]
