# Generated by Django 5.2.4 on 2025-09-14 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_coupon_order_discounted_total_order_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lipaprogramregistration',
            old_name='registered_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='lipaprogramregistration',
            name='approved_at',
        ),
        migrations.AddField(
            model_name='installmentorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 9, 14, 17, 19, 11, 952407, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='installmentorder',
            name='monthly_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='installmentorder',
            name='months',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='installmentorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lipaprogramregistration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='lipaprogramregistration',
            name='id_back',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lipaprogramregistration',
            name='id_front',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lipaprogramregistration',
            name='passport_photo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='discounted_total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('FULL', 'Full Payment'), ('INSTALLMENT', 'Installment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
