# Generated by Django 5.2.7 on 2025-10-17 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_delivery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
