# Generated by Django 5.2.4 on 2025-09-30 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_order_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
    ]
