# Generated by Django 5.2.4 on 2025-09-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_registered_at_lipaprogramregistration_created_at_and_more'),
    ]

    operations = [
    ]
