# Generated by Django 5.2.4 on 2025-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20250914_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lipaprogramregistration',
            name='id_back',
            field=models.FileField(upload_to='lipa_documents/id_back/'),
        ),
        migrations.AlterField(
            model_name='lipaprogramregistration',
            name='id_front',
            field=models.FileField(upload_to='lipa_documents/id_front/'),
        ),
        migrations.AlterField(
            model_name='lipaprogramregistration',
            name='passport_photo',
            field=models.FileField(upload_to='lipa_documents/passport/'),
        ),
    ]
