# Generated by Django 5.2.4 on 2025-09-15 09:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_lipaprogramregistration_id_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discounted_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
