# Generated by Django 5.2.7 on 2025-10-07 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_order_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
        migrations.AlterField(
            model_name='installmentorder',
            name='months',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='installmentorder',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installment_order', to='dashboard.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discounted_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('WALLET', 'Wallet'), ('CASH_ON_DELIVERY', 'Cash on Delivery'), ('INSTALLMENT', 'Installment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
