# Generated by Django 5.2.4 on 2025-09-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_order_discounted_total_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_processed',
            field=models.BooleanField(default=False),
        ),
    ]
