# Generated by Django 5.2.7 on 2025-10-09 14:07

import grandview.settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.ImageField(storage=grandview.settings.S3MediaStorage(), upload_to='packages/'),
        ),
    ]
